- rawRequest: |
    POST https://localhost:9443/api/am/publisher/v1/apis/import-openapi HTTP/1.1
    Content-Type: multipart/form-data; boundary="----=_Part_4_2096758352.1563880508761"
    Authorization: Bearer 031cf7d6-4f49-3089-a164-5289b171203a
    Content-Length: 2972


      ------=_Part_4_2096758352.1563880508761
    Content-Disposition: form-data; name="additionalProperties"

      { "name": "PetstoreAPI", "context" : "/petstore", "version" : "1.0.0"}
      ------=_Part_4_2096758352.1563880508761
    Content-Type: application/octet-stream; name=petstore.v3.yaml
    Content-Transfer-Encoding: binary
    Content-Disposition: form-data; name="file"; filename="petstore.v3.yaml"

    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Swagger Petstore
      license:
        name: MIT
    servers:
      - url: http://petstore.swagger.io/v1
    paths:
      /pets:
        get:
          summary: List all pets
          operationId: listPets
          tags:
            - pets
          parameters:
            - name: limit
              in: query
              description: How many items to return at one time (max 100)
              required: false
              schema:
                type: integer
                format: int32
          responses:
            '200':
              description: A paged array of pets
              headers:
                x-next:
                  description: A link to the next page of responses
                  schema:
                    type: string
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Pets"
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
        post:
          summary: Create a pet
          operationId: createPets
          tags:
            - pets
          responses:
            '201':
              description: Null response
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
      /pets/{petId}:
        get:
          summary: Info for a specific pet
          operationId: showPetById
          tags:
            - pets
          parameters:
            - name: petId
              in: path
              required: true
              description: The id of the pet to retrieve
              schema:
                type: string
          responses:
            '200':
              description: Expected response to a valid request
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Pet"
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
    components:
      schemas:
        Pet:
          required:
            - id
            - name
          properties:
            id:
              type: integer
              format: int64
            name:
              type: string
            tag:
              type: string
        Pets:
          type: array
          items:
            $ref: "#/components/schemas/Pet"
        Error:
          required:
            - code
            - message
          properties:
            code:
              type: integer
              format: int32
            message:
              type: string
      ------=_Part_4_2096758352.1563880508761--


  curl: |
    curl -k -H "Authorization: Bearer 031cf7d6-4f49-3089-a164-5289b171203a" -F file=@petstore.v3.yaml -F additionalProperties='{ "name": "PetstoreAPI", "context" : "/petstore", "version" : "1.0.0"}' -X POST https://localhost:9443/api/am/publisher/v1/apis/import-openapi
  rawResponse: |
    HTTP/1.1 201 Created
    Location: https://localhost:9443/api/am/publisher/v1/apis/ded1a2fd-1a56-4eab-ae5f-07f8df03b0bd
    Content-Type: application/json
    Transfer-Encoding: chunked

    {
      "id" : "089dac61-a58d-4eaf-9575-3beb5a8eec01",
      "name" : "PetstoreAPI",
      "description" : null,
      "context" : "/petstore",
      "version" : "1.0.0",
      "provider" : "admin",
      "lifeCycleStatus" : "CREATED",
      "wsdlUri" : null,
      "responseCaching" : null,
      "cacheTimeout" : 300,
      "destinationStatsEnabled" : null,
      "hasThumbnail" : null,
      "isDefaultVersion" : false,
      "type" : "HTTP",
      "transport" : [
        "http",
        "https"
      ],
      "tags" : [ ],
      "policies" : [ ],
      "apiThrottlingPolicy" : "Unlimited",
      "authorizationHeader" : null,
      "securityScheme" : [
        "oauth2",
        "oauth_basic_auth_mandatory"
      ],
      "maxTps" : null,
      "visibility" : "PUBLIC",
      "visibleRoles" : [ ],
      "visibleTenants" : [ ],
      "endpointSecurity" : null,
      "gatewayEnvironments" : [ ],
      "labels" : [ ],
      "mediationPolicies" : [ ],
      "subscriptionAvailability" : "ALL_TENANTS",
      "subscriptionAvailableTenants" : [ ],
      "additionalProperties" : { },
      "monetization" : null,
      "accessControl" : "NONE",
      "accessControlRoles" : [ ],
      "businessInformation" : {
        "businessOwner" : null,
        "businessOwnerEmail" : null,
        "technicalOwner" : null,
        "technicalOwnerEmail" : null
      },
      "corsConfiguration" : {
        "corsConfigurationEnabled" : false,
        "accessControlAllowOrigins" : [
          "*"
        ],
        "accessControlAllowCredentials" : false,
        "accessControlAllowHeaders" : [
          "authorization",
          "Access-Control-Allow-Origin",
          "Content-Type",
          "SOAPAction"
        ],
        "accessControlAllowMethods" : [
          "GET",
          "PUT",
          "POST",
          "DELETE",
          "PATCH",
          "OPTIONS"
        ]
      },
      "workflowStatus" : null,
      "createdTime" : null,
      "lastUpdatedTime" : null,
      "endpointConfig" : null,
      "scopes" : [ ],
      "operations" : [
      {
        "id" : "",
        "uritemplate" : "/pets",
        "httpVerb" : "POST",
        "authType" : "Application & Application User",
        "throttlingPolicy" : "Unlimited",
        "scopes" : [ ]
      },
      {
        "id" : "",
        "uritemplate" : "/pets",
        "httpVerb" : "GET",
        "authType" : "Application & Application User",
        "throttlingPolicy" : "Unlimited",
        "scopes" : [ ]
      },
      {
        "id" : "",
        "uritemplate" : "/pets/{petId}",
        "httpVerb" : "GET",
        "authType" : "Application & Application User",
        "throttlingPolicy" : "Unlimited",
        "scopes" : [ ]
      }
      ],
      "threatProtectionPolicies" : null
    }


- title: Importing an API with a subset of operations
  rawRequest: |
    POST https://localhost:9443/api/am/publisher/v1/apis/import-openapi HTTP/1.1
    Accept-Encoding: gzip,deflate
    Content-Type: multipart/form-data; boundary="----=_Part_3_xxxx.xxxxxxx"
    MIME-Version: 1.0
    Authorization: Bearer 031cf7d6-4f49-3089-a164-5289b171203a
    Content-Length: xxxx
    Host: localhost:9443


      ------=_Part_3_163462078.1563876620605
    Content-Disposition: form-data; name="additionalProperties"

      {
         "name":"PetstoreAPI",
         "context":"/petstore",
         "version":"1.0.0",
         "operations":[
            {
               "id":"",
               "uritemplate":"/pets",
               "httpVerb":"POST",
               "authType":"Application & Application User",
               "throttlingPolicy":"Unlimited",
               "scopes":[

               ]
            }
         ]
      }
      ------=_Part_3_xxxxx.xxxxx
    Content-Type: application/octet-stream; name=petstore.v3.yaml
    Content-Transfer-Encoding: binary
    Content-Disposition: form-data; name="file"; filename="petstore.v3.yaml"

    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Swagger Petstore
      license:
        name: MIT
    servers:
      - url: http://petstore.swagger.io/v1
    paths:
      /pets:
        get:
          summary: List all pets
          operationId: listPets
          tags:
            - pets
          parameters:
            - name: limit
              in: query
              description: How many items to return at one time (max 100)
              required: false
              schema:
                type: integer
                format: int32
          responses:
            '200':
              description: A paged array of pets
              headers:
                x-next:
                  description: A link to the next page of responses
                  schema:
                    type: string
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Pets"
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
        post:
          summary: Create a pet
          operationId: createPets
          tags:
            - pets
          responses:
            '201':
              description: Null response
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
      /pets/{petId}:
        get:
          summary: Info for a specific pet
          operationId: showPetById
          tags:
            - pets
          parameters:
            - name: petId
              in: path
              required: true
              description: The id of the pet to retrieve
              schema:
                type: string
          responses:
            '200':
              description: Expected response to a valid request
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Pet"
            default:
              description: unexpected error
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/Error"
    components:
      schemas:
        Pet:
          required:
            - id
            - name
          properties:
            id:
              type: integer
              format: int64
            name:
              type: string
            tag:
              type: string
        Pets:
          type: array
          items:
            $ref: "#/components/schemas/Pet"
        Error:
          required:
            - code
            - message
          properties:
            code:
              type: integer
              format: int32
            message:
              type: string
      ------=_Part_3_xxxx.xxxxxx--

  curl: |
    curl -k -H "Authorization: Bearer 031cf7d6-4f49-3089-a164-5289b171203a" -F file=@petstore.v3.yaml -F additionalProperties='{ "name": "PetstoreAPI", "context" : "/petstore", "version" : "1.0.0" , "operations": [{ "uritemplate": "/pets", "httpVerb": "POST", "authType": "Application & Application User", "throttlingPolicy": "Unlimited", "scopes": []}]}' -X POST https://localhost:9443/api/am/publisher/v1/apis/import-openapi
  rawResponse: |
    HTTP/1.1 201 Created
    Location: https://localhost:9443/api/am/publisher/v1/apis/ded1a2fd-1a56-4eab-ae5f-07f8df03b0bd
    Content-Type: application/json
    Transfer-Encoding: chunked

    {
      "id" : "ded1a2fd-1a56-4eab-ae5f-07f8df03b0bd",
      "name" : "PetstoreAPI",
      "description" : null,
      "context" : "/petstore",
      "version" : "1.0.0",
      "provider" : "admin",
      "lifeCycleStatus" : "CREATED",
      "wsdlUri" : null,
      "responseCaching" : null,
      "cacheTimeout" : 300,
      "destinationStatsEnabled" : null,
      "hasThumbnail" : null,
      "isDefaultVersion" : false,
      "type" : "HTTP",
      "transport" : [
        "http",
        "https"
      ],
      "tags" : [ ],
      "policies" : [ ],
      "apiThrottlingPolicy" : "Unlimited",
      "authorizationHeader" : null,
      "securityScheme" : [
        "oauth2",
        "oauth_basic_auth_mandatory"
      ],
      "maxTps" : null,
      "visibility" : "PUBLIC",
      "visibleRoles" : [ ],
      "visibleTenants" : [ ],
      "endpointSecurity" : null,
      "gatewayEnvironments" : [ ],
      "labels" : [ ],
      "mediationPolicies" : [ ],
      "subscriptionAvailability" : "ALL_TENANTS",
      "subscriptionAvailableTenants" : [ ],
      "additionalProperties" : { },
      "monetization" : null,
      "accessControl" : "NONE",
      "accessControlRoles" : [ ],
      "businessInformation" : {
        "businessOwner" : null,
        "businessOwnerEmail" : null,
        "technicalOwner" : null,
        "technicalOwnerEmail" : null
      },
      "corsConfiguration" : {
        "corsConfigurationEnabled" : false,
        "accessControlAllowOrigins" : [
          "*"
        ],
        "accessControlAllowCredentials" : false,
        "accessControlAllowHeaders" : [
          "authorization",
          "Access-Control-Allow-Origin",
          "Content-Type",
          "SOAPAction"
        ],
        "accessControlAllowMethods" : [
          "GET",
          "PUT",
          "POST",
          "DELETE",
          "PATCH",
          "OPTIONS"
        ]
      },
      "workflowStatus" : null,
      "createdTime" : null,
      "lastUpdatedTime" : null,
      "endpointConfig" : null,
      "scopes" : [ ],
      "operations" : [
      {
        "id" : "",
        "uritemplate" : "/pets",
        "httpVerb" : "POST",
        "authType" : "Application & Application User",
        "throttlingPolicy" : "Unlimited",
        "scopes" : [ ]
      }
      ],
      "threatProtectionPolicies" : null
    }
