appName : API Editor
theme : "org.wso2.carbon.apimgt.web.publisher.theme.default"
title : "API Editor Tool"
menu :
  main :
    Home : {link: "", icon: "fw-home"}
  left :
    APIs : { link: "", icon: "fw-home"}
    Applications: {link: "applications"}
    Forum: { link: "forum"}
    Statistics:
      {link: "statistics"}
errorPages:
  "404": /ui/error/404
  default: /ui/error/default
loginRedirectUri: "/api"
swaggerURL: "http://localhost:9090/swagger?path=/api/am/publisher/v0.10/apis"