name: Test Coverage Uploader

on:
  schedule:
    - cron:  '0 20 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Run hostname
      run: hostname
    - name: Fix host entry
      run: sudo echo "127.0.0.1 $(hostname)" | sudo tee -a /etc/hosts
    - name: Show hosts
      run: cat /etc/hosts
    - name: Checkout master
      uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: 'adopt'
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Build carbon-apimgt with Tests, skipping AspectJ
      run: mvn clean install --file pom.xml -Dskip.aspectj=true
    - name: Get carbon.apimgt.version
      run: mvn help:evaluate -Dexpression=project.version -q -DforceStdout > ../CARBON_APIMGT_VERSION_FILE
    - name: Print carbon.apimgt.version
      run: |
        echo $(cat ../CARBON_APIMGT_VERSION_FILE)
    - name: Checkout Product-APIM
      uses: actions/checkout@v1
      with: 
        repository: wso2/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Tests
      continue-on-error: true
      run: mvn clean install -Dcarbon.apimgt.version=$(cat ../CARBON_APIMGT_VERSION_FILE) -fae --file ../product-apim/pom.xml
    - name: Upload unit test coverage to Codecov
      uses: codecov/codecov-action@v1.2.1
      with:
        flags: unit_tests
    - name: Upload integration test coverage to Codecov
      uses: codecov/codecov-action@v1.2.1
      with:
        flags: integration_tests
        directory: ../product-apim/
