name: API Manager Build with Test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8.0.172
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Build carbon-apimgt with Test.
      run: mvn clean install --file pom.xml
    - name: Get carbon.apimgt.version
      run: mvn help:evaluate -Dexpression=project.version -q -DforceStdout > ../CARBON_APIMGT_VERSION_FILE
    - name: Print carbon.apimgt.version
      run: |
        echo $(cat ../CARBON_APIMGT_VERSION_FILE)
    - name: Checkout Product-APIM
      uses: actions/checkout@v1
      with: 
        repository: wso2/product-apim
        ref: refs/heads/master
    - name: Build Product-Apim with Maven
      run: mvn clean install -Dcarbon.apimgt.version=$(cat ../CARBON_APIMGT_VERSION_FILE) -fae --file ../product-apim/pom.xml
